const SERIES = {
  name: "Puzmania",
  show: "Field Notes",
  tagline: "One episode a day on YouTube and Instagram.",
};

const DEFAULT_SETTINGS = {
  publishTime: "09:00",
  timezone: "Asia/Karachi",
  episodesPerRun: 1,
  retryAttempts: 3,
  retryBackoff: "exponential",
  notifyEmail: true,
  notifySlack: false,
  alertOnFailure: true,
  dryRun: true,
  winnerMode: "seed",
  pointsMultiplier: 2500,
  winnerIntroDays: 3,
  platforms: {
    youtube: { enabled: true, connected: false },
    tiktok: { enabled: false, connected: false },
    instagram: { enabled: true, connected: false },
  },
};

const PLATFORMS = [
  {
    id: "youtube",
    name: "YouTube",
    api: "Data API v3",
    method: "videos.insert · thumbnails.set",
    note: "OAuth consent is required once per channel. Upload quota is sufficient for one video a day.",
  },
  {
    id: "tiktok",
    name: "TikTok",
    api: "Content Posting API",
    method: "Direct Post",
    note: "Unaudited apps can only post privately. Public auto-publish needs TikTok’s compliance audit.",
  },
  {
    id: "instagram",
    name: "Instagram",
    api: "Graph API",
    method: "local file → Reels container → publish",
    note: "Crops the episode .mp4 to a full-bleed 9:16 reel, then publishes. ChatGPT writes the caption first.",
  },
];

const EPISODES = [
  {
    id: "EP001",
    title: "First Light Over the Harbour",
    description: "A quiet open: docks at dawn, radio chatter, and the first map of the season.",
    tags: ["documentary", "harbour", "dawn"],
    filename: "EP001_first-light.mp4",
    duration: "12:04",
    scheduled: "2026-08-03",
    youtube: { status: "success", id: "dQwY8nHarbour1" },
    tiktok: { status: "success", id: "tt_748201" },
    instagram: { status: "success", id: "ig_192837" },
    publishedAt: "2026-08-03T09:04:12",
  },
  {
    id: "EP002",
    title: "The Last Independent Bookshop",
    description: "Shelves, dust, and a bookseller who still wraps every purchase by hand.",
    tags: ["city", "books", "portrait"],
    filename: "EP002_bookshop.mp4",
    duration: "11:41",
    scheduled: "2026-08-04",
    youtube: { status: "success", id: "yt_bookshop02" },
    tiktok: { status: "success", id: "tt_748202" },
    instagram: { status: "success", id: "ig_192838" },
    publishedAt: "2026-08-04T09:03:44",
  },
  {
    id: "EP003",
    title: "Maps Without Borders",
    description: "Cartographers, faded atlases, and the argument over what a coastline is.",
    tags: ["maps", "history", "essay"],
    filename: "EP003_maps.mp4",
    duration: "13:22",
    scheduled: "2026-08-05",
    youtube: { status: "success", id: "yt_maps03" },
    tiktok: { status: "success", id: "tt_748203" },
    instagram: { status: "success", id: "ig_192839" },
    publishedAt: "2026-08-05T09:05:01",
  },
  {
    id: "EP004",
    title: "Night Shift at the Signal Tower",
    description: "Headphones, tea, and a wall of frequencies that never quite go quiet.",
    tags: ["night", "radio", "work"],
    filename: "EP004_signal-tower.mp4",
    duration: "10:58",
    scheduled: "2026-08-06",
    youtube: { status: "success", id: "yt_signal04" },
    tiktok: { status: "success", id: "tt_748204" },
    instagram: { status: "success", id: "ig_192840" },
    publishedAt: "2026-08-06T09:02:19",
  },
  {
    id: "EP005",
    title: "A Kitchen the Size of a Postcard",
    description: "One burner, three recipes, and the discipline of cooking for one.",
    tags: ["food", "city", "routine"],
    filename: "EP005_kitchen.mp4",
    duration: "09:47",
    scheduled: "2026-08-07",
    youtube: { status: "success", id: "yt_kitchen05" },
    tiktok: { status: "success", id: "tt_748205" },
    instagram: { status: "success", id: "ig_192841" },
    publishedAt: "2026-08-07T09:06:33",
  },
  {
    id: "EP006",
    title: "Rain on the Northbound Line",
    description: "Carriage windows, delayed announcements, and a letter that never gets sent.",
    tags: ["train", "weather", "travel"],
    filename: "EP006_northbound.mp4",
    duration: "12:31",
    scheduled: "2026-08-10",
    youtube: { status: "success", id: "yt_train06" },
    tiktok: { status: "success", id: "tt_748206" },
    instagram: { status: "success", id: "ig_192842" },
    publishedAt: "2026-08-10T09:03:08",
  },
  {
    id: "EP007",
    title: "The Conservatory After Closing",
    description: "Glasshouse humidity, moths against the lamps, a pianist warming up alone.",
    tags: ["music", "night", "architecture"],
    filename: "EP007_conservatory.mp4",
    duration: "14:02",
    scheduled: "2026-08-11",
    youtube: { status: "success", id: "yt_cons07" },
    tiktok: { status: "success", id: "tt_748207" },
    instagram: { status: "success", id: "ig_192843" },
    publishedAt: "2026-08-11T09:04:51",
  },
  {
    id: "EP008",
    title: "Archive Dust",
    description: "A municipal cellar of tapes, a failing index, and one reel that should not exist.",
    tags: ["archive", "mystery", "city"],
    filename: "EP008_archive-dust.mp4",
    duration: "13:18",
    scheduled: "2026-08-14",
    youtube: { status: "success", id: "yt_archive08" },
    tiktok: { status: "failed", id: null, error: "App is unaudited — Direct Post is limited to private visibility." },
    instagram: { status: "success", id: "ig_192844" },
    publishedAt: null,
    retryCount: 3,
    lastError: "TikTok: unaudited app cannot publish publicly.",
  },
  {
    id: "EP009",
    title: "Letters from a Closed Station",
    description: "Unclaimed mail, a boarded ticket hall, and names that no longer match the platform.",
    tags: ["letters", "station", "essay"],
    filename: "EP009_closed-station.mp4",
    duration: "11:26",
    scheduled: "2026-08-15",
    youtube: { status: "pending", id: null },
    tiktok: { status: "pending", id: null },
    instagram: { status: "pending", id: null },
    publishedAt: null,
  },
  {
    id: "EP010",
    title: "The Bridge That Was Never Named",
    description: "Concrete, river fog, and the people who cross it twice a day without looking up.",
    tags: ["bridge", "city", "portrait"],
    filename: "EP010_unnamed-bridge.mp4",
    duration: "10:12",
    scheduled: "2026-08-16",
    youtube: { status: "pending", id: null },
    tiktok: { status: "pending", id: null },
    instagram: { status: "pending", id: null },
    publishedAt: null,
  },
  {
    id: "EP011",
    title: "Winter Fruit in August",
    description: "A grocer who imports seasons, and the ethics of a perfect pear.",
    tags: ["food", "trade", "city"],
    filename: "EP011_winter-fruit.mp4",
    duration: "09:55",
    scheduled: "2026-08-17",
    youtube: { status: "pending", id: null },
    tiktok: { status: "pending", id: null },
    instagram: { status: "pending", id: null },
    publishedAt: null,
  },
  {
    id: "EP012",
    title: "A Room Above the Printers",
    description: "Ink in the stairwell, overnight proofs, and the last linotype in the district.",
    tags: ["print", "work", "night"],
    filename: "EP012_printers.mp4",
    duration: "12:47",
    scheduled: "2026-08-18",
    youtube: { status: "pending", id: null },
    tiktok: { status: "pending", id: null },
    instagram: { status: "pending", id: null },
    publishedAt: null,
  },
];

const HISTORY = [
  { at: "2026-08-14T09:06:41", episode: "EP008", platform: "tiktok", result: "failed", detail: "Unaudited app — public Direct Post denied. Marked for review after 3 retries." },
  { at: "2026-08-14T09:05:12", episode: "EP008", platform: "instagram", result: "success", detail: "Reel published · ig_192844" },
  { at: "2026-08-14T09:04:02", episode: "EP008", platform: "youtube", result: "success", detail: "Public · yt_archive08 · thumbnail set" },
  { at: "2026-08-14T09:00:00", episode: "EP008", platform: "system", result: "info", detail: "Daily run started. Dry-run off in production; this log is sample history." },
  { at: "2026-08-11T09:04:51", episode: "EP007", platform: "system", result: "success", detail: "All three platforms succeeded. Summary mailed." },
  { at: "2026-08-10T09:03:08", episode: "EP006", platform: "system", result: "success", detail: "All three platforms succeeded. Summary mailed." },
  { at: "2026-08-07T09:06:33", episode: "EP005", platform: "system", result: "success", detail: "All three platforms succeeded. Summary mailed." },
];
